version: "3.3"

services:
  jenkins:
    build:
      context: ./master
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc_configs:/var/jenkins_conf
    secrets:
      - GITHUB
      - COMPUTE_ENGINE_SA
      - JENKINS_USER
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf

secrets:
  GITHUB:
    file: /shared/jenkins/JenkinsCasC/secrets/github
  COMPUTE_ENGINE_SA:
    file: /shared/jenkins/JenkinsCasC/secrets/cred
  JENKINS_USER:
    file: /shared/jenkins/JenkinsCasC/secrets/jenkins

volumes:
  jenkins_home:
