version: "3.3"

services:
  jenkins:
    build:
      context: ./master
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc_configs:/var/jenkins_conf
    secrets:
      - GITHUB
      - COMPUTE_ENGINE_SA
      - JENKINS_USER
      - TOMCAT_MANAGER
      - APP_ENGINE_SA
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
      - SONAR_TOKEN

secrets:
  GITHUB:
    file: /shared/jenkins/JenkinsCasC/secrets/github
  COMPUTE_ENGINE_SA:
    file: /shared/jenkins/JenkinsCasC/secrets/cred
  JENKINS_USER:
    file: /shared/jenkins/JenkinsCasC/secrets/jenkins
  TOMCAT_MANAGER:
    file: /shared/jenkins/JenkinsCasC/secrets/tomcat
  APP_ENGINE_SA:
    file: /shared/jenkins/JenkinsCasC/secrets/appEngineSecret

volumes:
  jenkins_home:
