credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: "Login details for Github"
              id: "GitHubLogin"
              password: ${GITHUB}
              scope: GLOBAL
              username: "yas.hashmi@gmail.com"
          - usernamePassword:
              description: "Tomcat Apache Manager creds"
              id: "tomcat-manager"
              password: ${TOMCAT_MANAGER}
              scope: GLOBAL
              username: "tomcat"
          - googleRobotPrivateKey:
              projectId: "jenkins-325510"
              serviceAccountConfig:
                json:
                  #filename: ${compute_engine_sa}
                  secretJsonKey: ${COMPUTE_ENGINE_SA}
          - file:
              description: "Service Account Key for App Engine Deployment"
              fileName: "appengine_ce_sa_key.json"
              id: "AppEngineServiceKey"
              scope: GLOBAL
              secretBytes: ${APP_ENGINE_SA}

jenkins:
  systemMessage: "\n\nWelcome to the Jenkins!\n\n"

  numExecutors: 0
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"

  # views:
  #   - workflowPipeline:
  #       componentSpecs:
  #       - job: "UtilityChargesPipelineTomcat"
  #         name: "Full pipeline"
  #       name: "UtilityCharges Pipeline"
  #       noOfColumns: 3
  #       showChanges: true
  #       updateInterval: 5
  #   - all:
  #       name: "all"
  # viewsTabBar: "standard"
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: JenkinsUser
          password: ${JENKINS_USER}
          properties:
          - timezone:
              timeZoneName: "Asia/Calcutta"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false

  remotingSecurity:
    enabled: true

  globalNodeProperties:
    - envVars:
        env:
          - key: "SONAR_TOKEN"
            value: ${SONAR_TOKEN}

  clouds:
    - computeEngine:
        cloudName: "gce"
        configurations:
          - bootDiskAutoDelete: true
            bootDiskSizeGb: 10
            bootDiskSizeGbStr: "10"
            bootDiskSourceImageName: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/global/images/java-build-node-jenkins-v3"
            bootDiskSourceImageProject: "jenkins-325510"
            bootDiskType: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/zones/us-central1-f/diskTypes/pd-balanced"
            description: "Ubuntu Java 11 build stack agent for Jenkins"
            javaExecPath: "java"
            labelSet:
              - name: "Java11"
            labelString: "Java11"
            labels: "Java11"
            externalAddress: true
            launchTimeoutSeconds: 300
            launchTimeoutSecondsStr: "300"
            machineType: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/zones/us-central1-f/machineTypes/n1-standard-1"
            mode: NORMAL
            namePrefix: "ubuntu-java11"
            networkConfiguration:
              autofilled:
                network: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/global/networks/custom-network"
                subnetwork: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/regions/us-central1/subnetworks/us-central"
            networkTags: "ssh"
            numExecutors: 1
            numExecutorsStr: "1"
            region: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/regions/us-central1"
            retentionTimeMinutes: 6
            retentionTimeMinutesStr: "6"
            runAsUser: "jenkins"
            useInternalAddress: true
            zone: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/zones/us-central1-f"
          - bootDiskAutoDelete: true
            bootDiskSizeGb: 10
            bootDiskSizeGbStr: "10"
            bootDiskSourceImageName: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/global/images/docker-image-jenkins-v1"
            bootDiskSourceImageProject: "jenkins-325510"
            bootDiskType: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/zones/us-central1-c/diskTypes/pd-balanced"
            description: "A tomcat server"
            externalAddress: true
            javaExecPath: "java"
            labelSet:
              - name: "tomcat9"
            labelString: "tomcat9"
            labels: "tomcat9"
            launchTimeoutSeconds: 300
            launchTimeoutSecondsStr: "300"
            machineType: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/zones/us-central1-c/machineTypes/n1-standard-1"
            mode: NORMAL
            namePrefix: "tomcat-server"
            networkConfiguration:
              autofilled:
                network: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/global/networks/custom-network"
                subnetwork: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/regions/us-central1/subnetworks/us-central"
            networkTags: "ssh http-server"
            numExecutors: 1
            numExecutorsStr: "1"
            region: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/regions/us-central1"
            retentionTimeMinutes: 6
            retentionTimeMinutesStr: "6"
            runAsUser: "jenkins"
            zone: "https://www.googleapis.com/compute/v1/projects/jenkins-325510/zones/us-central1-c"
        credentialsId: "jenkins-325510"
        instanceCapStr: "2"
        instanceId: "f301d0f9-aed2-4e1c-a95b-8272f4c31e26"
        projectId: "jenkins-325510"

unclassified:
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    globalConfigEmail: "yas.hashmi@gmail.com"
    globalConfigName: "Yasub Hashmi"
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false

tool:
  git:
    installations:
      - name: Default
        home: "git"

jobs:
  - file: /var/jenkins_conf/utilityChargesPipeline.groovy
